#redis 配置
spring:
    redis:
      database: 1
      host: localhost
      port: 6379
      password: 
      timeout: 1000
      jedis:
        pool:
          max-active: 1000
          max-wait: -1
          max-idle: 10
          min-idle: 2