# 数据库配置
spring:
  datasource:
   url: jdbc:mysql://192.168.3.64:3306/shiro_restful?useSSL=false&useUnicode=true&characterEncoding=utf-8
   username: root
   password: 123456
    # tomcat:
   #      initSQL: SET NAMES utf8mb4 COLLATE utf8mb4_unicode_ci
   driver-class-name: com.mysql.jdbc.Driver

#连接池的配置信息
#https://github.com/alibaba/druid/wiki/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98
#连接池项目地址:https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
   druid:
      initial-size: 2
      min-idle: 2
      max-active: 20
      test-on-borrow: true
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 5
      async-close-connection-enable: true


#mybatis:
# configuration:
#  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql





#redis 配置
  redis:
    database: 2
    host: localhost
    port: 6379
    password:
    timeout: 1000
    jedis:
      pool:
        max-active: 1000
        max-wait: -1
        max-idle: 10
        min-idle: 2
        
